package com.dtech.aitrader.data;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Represents a paper (simulated) trade created by a pattern agent decision.
 * Tracks entry, exit, and P&L for all trades generated by AI agents.
 */
@Entity
@Table(name = "paper_trade")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PaperTrade {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column
    private Long agentDecisionId;

    @Column(nullable = false, length = 32)
    private String symbol;

    @Column(nullable = false, length = 8)
    private String direction; // "LONG" | "SHORT"

    @Column(nullable = false, precision = 12, scale = 2)
    private BigDecimal entryPrice;

    @Column(nullable = false, precision = 12, scale = 2)
    private BigDecimal sl;

    @Column(nullable = false, precision = 12, scale = 2)
    private BigDecimal target;

    @Column(nullable = false)
    private LocalDateTime openedAt;

    @Column
    private LocalDateTime closedAt;

    @Column(precision = 12, scale = 2)
    private BigDecimal exitPrice;

    @Column(length = 16)
    private String exitReason; // "TARGET", "STOP", "TIME_STOP", "MANUAL_CLOSE"

    @Column
    private Double pnlPct;

    @Column(nullable = false, length = 16)
    private String status; // "OPEN", "CLOSED"

    @Column(nullable = false)
    private LocalDateTime createdAt;
}
