package com.dtech.ta.elliott;

import lombok.Builder;
import lombok.Data;

import java.util.List;
import java.util.Map;

/**
 * The complete output of the Elliott Wave engine for one analysis run.
 *
 * This is the data structure passed to the AI reasoning layer (Layer 9).
 * It contains all scenarios, hypotheses, patterns, and enriched pivots —
 * everything the AI needs to rank, contextualize, and produce trade ideas.
 */
@Data
@Builder
public class ElliottWaveAnalysis {

    /** The primary timeframe this analysis focuses on */
    private String primaryTimeframe;

    /** All timeframes analyzed (highest → lowest) */
    private List<String> timeframes;

    /**
     * All generated scenarios, sorted by highest hypothesis score descending.
     * The AI should consider ALL scenarios — not just the top one.
     */
    private List<WaveScenario> scenarios;

    /**
     * All detected/building chart patterns across all timeframes.
     * Includes BUILDING (first pivot), WATCHING (waiting for breakout), and CONFIRMED.
     */
    private List<PatternMatch> allPatterns;

    /** Enriched pivots per timeframe (for detailed indicator inspection if needed) */
    private Map<String, List<EnrichedPivot>> enrichedPivots;

    /** All valid wave counts before grouping into scenarios */
    private List<WaveCount> waveCounts;

    /** Unfilled/partially-filled price gaps per timeframe */
    @Builder.Default
    private java.util.Map<String, List<GapLevel>> gapsByTf = new java.util.LinkedHashMap<>();

    /** All significant (non-minor) gaps across all timeframes */
    @Builder.Default
    private List<GapLevel> significantGaps = new java.util.ArrayList<>();

    /** Cross-timeframe narrative generated by ElliottWaveAnalyzer */
    private String crossTfNarrative;

    /**
     * Explicit nested corrective branch context.
     * This captures higher-degree pathing such as W4 -> B -> C of B and
     * the live alternates (truncation vs extension).
     */
    private String nestedBranchNarrative;

    /** TfContext per timeframe (top-down constraint + bottom-up confirmations) */
    @Builder.Default
    private java.util.Map<String, TfContext> tfContexts = new java.util.LinkedHashMap<>();

    /** Explicit higher-degree corrective nesting inferred from the flatter engine output. */
    @Builder.Default
    private List<NestedWaveContext> nestedCorrectiveContexts = new java.util.ArrayList<>();

    /** Virgin (never-retested) trendlines connecting key wave structural pivots */
    @Builder.Default
    private List<com.dtech.ta.trendline.VirginTrendline> virginTrendlines = new java.util.ArrayList<>();

    // ── Convenience accessors ─────────────────────────────────────────────────

    public WaveScenario topScenario() {
        return scenarios == null || scenarios.isEmpty() ? null : scenarios.get(0);
    }

    public List<PatternMatch> confirmedPatterns() {
        return allPatterns == null ? List.of()
                : allPatterns.stream().filter(p -> p.getStatus() == PatternStatus.CONFIRMED).toList();
    }

    public List<PatternMatch> buildingPatterns() {
        return allPatterns == null ? List.of()
                : allPatterns.stream().filter(p -> p.getStatus() == PatternStatus.BUILDING
                                                || p.getStatus() == PatternStatus.WATCHING).toList();
    }

    /**
     * Generates a concise text summary for inclusion in the AI prompt.
     * Keeps token count low while giving AI the essential context.
     */
    public String toPromptSummary() {
        StringBuilder sb = new StringBuilder();
        sb.append("=== ELLIOTT WAVE ENGINE (").append(primaryTimeframe).append(") ===\n\n");

        if (crossTfNarrative != null && !crossTfNarrative.isBlank())
            sb.append(crossTfNarrative).append("\n");

        if (nestedBranchNarrative != null && !nestedBranchNarrative.isBlank())
            sb.append(nestedBranchNarrative).append("\n");

        if (nestedCorrectiveContexts != null && !nestedCorrectiveContexts.isEmpty()) {
            sb.append("NESTED CORRECTIVE CONTEXT:\n");
            for (NestedWaveContext ctx : nestedCorrectiveContexts) {
                sb.append("  [").append(ctx.getTimeframe()).append("] ")
                  .append(ctx.getHigherDegreeWave()).append(" -> ")
                  .append(ctx.getCorrectiveLeg()).append(" -> ")
                  .append(ctx.getActiveSubwave()).append(" | ")
                  .append(ctx.getDominantStructure()).append("\n");
                sb.append("    ").append(ctx.getNarrative()).append("\n");
                for (NestedWaveContext.BranchHypothesis branch : ctx.getBranches()) {
                    sb.append("    - ").append(branch.getCode())
                      .append(" prob=").append(fmt(branch.getProbability() * 100)).append("%");
                    if (branch.getTargetLevel() != null) {
                        sb.append(" target=").append(fmt(branch.getTargetLevel()));
                    }
                    sb.append(" | ").append(branch.getLabel())
                      .append(" | next=").append(branch.getNextHigherDegreeMove()).append("\n");
                    if (branch.getTrigger() != null) {
                        sb.append("      Trigger: ").append(branch.getTrigger()).append("\n");
                    }
                    if (branch.getRationale() != null) {
                        sb.append("      Why: ").append(branch.getRationale()).append("\n");
                    }
                }
                if (ctx.getInvalidationLevel() != null) {
                    sb.append("    Invalidation anchor: ").append(fmt(ctx.getInvalidationLevel())).append("\n");
                }
            }
            sb.append("\n");
        }

        sb.append("COMPETING SCENARIOS — AI: assign probability weight to each, do NOT pick just one:\n\n");
        for (WaveScenario s : scenarios) {
            sb.append("[").append(s.getId()).append("] ").append(s.getDirectionLabel()).append("\n");
            for (WaveHypothesis h : s.getHypotheses()) {
                sb.append("  [").append(h.getId()).append("] score=").append(h.getTotalScore());
                if (h.getScoreBreakdown() != null && !h.getScoreBreakdown().isEmpty()) {
                    sb.append(" [");
                    h.getScoreBreakdown().forEach((k, v) -> sb.append(k).append("=").append(v).append(" "));
                    // trim trailing space and close bracket
                    int len = sb.length();
                    if (sb.charAt(len - 1) == ' ') sb.setCharAt(len - 1, ']');
                    else sb.append("]");
                }
                sb.append(" | ").append(h.getCurrentPositionDescription()).append("\n");
                if (h.getPrimaryTarget() != null)
                    sb.append("    Target: ").append(fmt(h.getPrimaryTarget().getLevel()))
                      .append(" (").append(h.getPrimaryTarget().getRatio()).append(")\n");
                sb.append("    Invalidation: ").append(fmt(h.getInvalidationLevel()))
                  .append(" — ").append(h.getInvalidationRule()).append("\n");
                if (!h.getSupportingEvidence().isEmpty()) {
                    sb.append("    + ");
                    h.getSupportingEvidence().stream().limit(4)
                     .forEach(e -> sb.append(e.getSource()).append(":").append(e.getObservation()).append("; "));
                    sb.append("\n");
                }
                if (!h.getContradictingEvidence().isEmpty()) {
                    sb.append("    - ");
                    h.getContradictingEvidence().stream().limit(3)
                     .forEach(e -> sb.append(e.getSource()).append(":").append(e.getObservation()).append("; "));
                    sb.append("\n");
                }
                if (!h.getMatchedPatterns().isEmpty()) {
                    sb.append("    ★ Pattern confluence: ");
                    h.getMatchedPatterns().forEach(p -> sb.append(p.getType()).append("[").append(p.getStatus()).append("] "));
                    sb.append("\n");
                }
            }
            sb.append("  Scenario floor: ").append(fmt(s.getScenarioInvalidation())).append("\n\n");
        }

        List<PatternMatch> building = buildingPatterns();
        if (!building.isEmpty()) {
            sb.append("BUILDING PATTERNS:\n");
            for (PatternMatch p : building) {
                sb.append("  ").append(p.getType()).append("[").append(p.getStatus()).append("] ")
                  .append(p.getTimeframe()).append(" conf=").append(fmt(p.getConfidence()))
                  .append(" | ").append(p.getDescription()).append("\n");
                if (p.getWaitingFor() != null) sb.append("    Waiting: ").append(p.getWaitingFor()).append("\n");
                if (p.getWaveContextHints() != null && !p.getWaveContextHints().isEmpty()) {
                    sb.append("    Wave context: ");
                    p.getWaveContextHints().forEach(h ->
                        sb.append(h.getImpliedCurrentPosition()).append("→").append(h.getImpliedNextWave())
                          .append("(").append(fmt(h.getProbability())).append(") "));
                    sb.append("\n");
                }
            }
            sb.append("\n");
        }

        List<PatternMatch> confirmed = confirmedPatterns();
        if (!confirmed.isEmpty()) {
            sb.append("CONFIRMED PATTERNS:\n");
            confirmed.forEach(p -> sb.append("  ").append(p.getType()).append(" ").append(p.getTimeframe())
                .append(" target=").append(p.getTarget() != null ? fmt(p.getTarget()) : "n/a")
                .append(" conf=").append(fmt(p.getConfidence())).append("\n"));
            sb.append("\n");
        }

        if (significantGaps != null && !significantGaps.isEmpty()) {
            double currentApprox = enrichedPivots == null ? 0 : enrichedPivots.values().stream()
                .flatMap(List::stream).mapToDouble(EnrichedPivot::getPrice).max().orElse(0);
            sb.append("GAP S/R ZONES:\n");
            significantGaps.stream().filter(g -> g.getGapMidpoint() > currentApprox).limit(4).forEach(g ->
                sb.append("  RESIST [").append(g.getTimeframe()).append("] ")
                  .append(fmt(g.getGapBottom())).append("–").append(fmt(g.getGapTop()))
                  .append(" ").append(g.getFillStatus()).append(" ").append(g.getSignificance())
                  .append(g.getVolumeRatio() >= 2 ? " [HIGH VOL]" : "").append("\n"));
            significantGaps.stream().filter(g -> g.getGapMidpoint() <= currentApprox).limit(4).forEach(g ->
                sb.append("  SUPPRT [").append(g.getTimeframe()).append("] ")
                  .append(fmt(g.getGapBottom())).append("–").append(fmt(g.getGapTop()))
                  .append(" ").append(g.getFillStatus()).append(" ").append(g.getSignificance())
                  .append(g.isNearCurrentPrice() ? " ★NEAR" : "")
                  .append(g.getVolumeRatio() >= 2 ? " [HIGH VOL]" : "").append("\n"));
            sb.append("\n");
        }

        return sb.toString();
    }

    private String fmt(double v) { return String.format("%.2f", v); }
}
