package com.dtech.ta.elliott.filter.domain;

public enum ScenarioFamilyType {
    BULLISH_CONTINUATION_AFTER_CORRECTION,
    BULLISH_CONTINUATION_AFTER_COMPRESSION,
    BEARISH_REVERSAL_AFTER_TERMINAL_PUSH,
    BEARISH_BREAKDOWN_AFTER_COMPRESSION,
    SIDEWAYS_COMPRESSION_BEFORE_BREAKOUT,
    ONGOING_CORRECTIVE_COMPLEXITY,
    MOTIVE_EXTENSION_STILL_ACTIVE,
    LOW_CONVICTION_REVERSAL_SEED,
    NO_TRADE_NOISE
}
